spring:
  main:
    sources: com.work.fb.FbRoutesApplication
    banner-mode: OFF
    
   
  activemq:
      broker-url: failover://tcp://10.142.129.23:61616
      user: admin
      password: admin
      pool:
       enabled: true
      
camel:
  springboot:
    xmlRoutes: classpath:com/routes/*.xml
    main-run-controller: true
    jmx-management-statistics-level: Default
    jmx-enabled: false
    endpoint-runtime-statistics-enabled: false
    name: FBRoutes
    
logging:
  config: classpath:logback.xml
  path: target
  
  
  
  # Customise active actuator endpoints
endpoints:
  configprops:
    enabled: false
  info:
    enabled: false
  shutdown:
    enabled: true
    
fb:
  appId: 1633262880316027
  appSecret: 76c7dc48241579ba5168b11db5327481
  userAccessToken: EAAXNcaXOWnsBABZBPghkyTZBvrZAAZByBFZCkhZCfoxyBSyQ0RHsDPsZAD766gTGneMfnJBDoVOpg4ZBo12eYQrriGpShlIwfbDmihs34TqUprkJOlx0pf1n1bWaXZCTzAS8bTSo07QmpvH3ex5UvZCR2I
  proxyEnabled: true
  proxyHost: proxy.cognizant.com
  proxyPort: 6050
  proxyUser: 115750
  proxyPassword: Spiti098
 