spring:
  main:
    sources: com.work.fb.FbRoutesApplication
    banner-mode: OFF
    
   
  activemq:
      broker-url: failover://tcp://10.142.129.23:61616
      user: admin
      password: admin
      pool:
       enabled: true
      
camel:
  springboot:
    xmlRoutes: classpath:com/routes/*.xml
    main-run-controller: true
    jmx-management-statistics-level: Default
    jmx-enabled: false
    endpoint-runtime-statistics-enabled: false
    name: FBRoutes
    
logging:
  config: classpath:logback.xml
  path: target
  
  
  
  # Customise active actuator endpoints
endpoints:
  configprops:
    enabled: false
  info:
    enabled: false
  shutdown:
    enabled: true
    
fb:
  appId: 1633262880316027
  appSecret: 76c7dc48241579ba5168b11db5327481
  userAccessToken: EAAXNcaXOWnsBANE8nM451IqE402fuNZAzXlaaJizFnP05S6zbDQAJWcwYRcEYNZBsCTwg7AowxgmP1DfUB3dzxN9HNaIpC5SqRABOz7ZCAW4gHY8LtqAUZBGxLw9Ll3rF7KHc2ZC4vf1ZC19rAbYbt8p5daG5MZCxIa4rNgFaMHaNKZCCjVetzSGlEHJknVksrcZD
  proxyEnabled: false
  proxyHost: proxy.cognizant.com
  proxyPort: 6050
  proxyUser: 115750
  proxyPassword: Spiti098
  fbPostHostIp: 35.164.126.228
  fbPostHostPort: 9999
  userTokenUri: http://35.164.126.228:9999/api/fb-u-tokens
 
 